Expose Hamiltonian Generation
QuEraComputing/bloqade-python pull request #941
Opened 2024-05-07 18:55 UTC by johnzl-777

This allows users to obtain the raw Hamiltonian generated by the program

2024-05-07 20:17 UTC, weinbe58 requested changes
Need to add some kind of test, maybe just make sure the hamiltonian for a single atom is correct.

2024-05-07 20:17 UTC, weinbe58 commented on src/bloqade/ir/routine/bloqade.py
> +        pass
```suggestion
```

2024-05-07 21:53 UTC, weinbe58 commented on src/bloqade/ir/routine/bloqade.py
> +        return MetaData(**{k: float(v) for k, v in self.metadata_dict.items()})
still not called here

2024-05-08 12:34 UTC, johnzl-777 commented
@weinbe58 I realize that with the new API I could go around and refactor all the tests in `test_hamiltonian_codege.py` to use it. 

I made a single test based off your `test_2_level_uniform_detuning` unit test for now but if you'd like me to proceed with the refactor after taking a look at what I've added, just let me know!

2024-05-09 14:44 UTC, merged