[Unitary-Hack][Task-Base] Docstring for "tasks/base"
QuEraComputing/bloqade-python pull request #970
Opened 2024-05-31 02:18 UTC by Manvi-Agrawal

Fixes #957

**Updated doc local preview**
[bloqade_doc_update.pdf](https://github.com/user-attachments/files/15537591/bloqade_doc_update.pdf)

2024-05-31 14:27 UTC, Roger-luo commented on src/bloqade/task/base.py
> +        """
this is a private method, there is no need to put docstring on it. As I mentioned we should write docstring for user space methods first.

2024-05-31 14:28 UTC, Roger-luo commented on src/bloqade/task/base.py
> +            Args:
This is not following the format in #956 and can we have an example?

2024-05-31 14:28 UTC, Roger-luo commented on src/bloqade/task/base.py
> +    Members:
```suggestion
    Fields:
```

2024-06-03 13:47 UTC, weinbe58 commented on src/bloqade/task/base.py
> +                all clusters are used, defaults to [].
you can't do this unfortunately because it breaks the mkdocs rendering rendering 😢

2024-06-03 14:27 UTC, Roger-luo commented on src/bloqade/task/base.py
> +    ```
just use the terminal style in one code block? e.g

```suggestion
    ```python
    >>> report.bitstrings()
    [array([[1, 1],
            [1, 1],
            [1, 1],
            ...,
            [1, 1],
            [1, 1],
            [1, 0]], dtype=int8)]
    ```
```

2024-06-03 19:46 UTC, Roger-luo commented on src/bloqade/task/base.py
> +    * The raw bitstrings measured per each execution of the program
I think we can omit bullet points, just plain text is fine

```suggestion
    The raw bitstrings measured per each execution of the program
```

2024-06-03 19:46 UTC, Roger-luo commented on src/bloqade/task/base.py
> +                all clusters are used, defaults to [].
I think as long as it renders this is fine.

2024-06-03 19:47 UTC, Roger-luo commented on src/bloqade/task/base.py
> +                0            0.053  0.054
put this as a separate example? it may not render nicely for multi-line code blocks within the method signature table.

2024-06-03 19:48 UTC, Roger-luo requested changes
sorry I think there are only one last changes for the format. I think I go through more carefully this time.

2024-06-03 20:49 UTC, Roger-luo approved these changes
I think this is good to merge. There are 8 docstrings being changed/added in this PR. While I may not want to recognize the one-liners counted but other docstrings are well written. So I think it's probably still fair to count this PR as a 32 USD bounty.

Just waiting CIs to pass.

2024-06-03 20:49 UTC, Roger-luo commented on src/bloqade/task/base.py
> +                0            0.053  0.054
Ok I think that's fine then.

2024-06-03 20:50 UTC, Roger-luo commented
> I have unrelated suggestion. I think it would be nice to have [Live Reloading](https://www.mkdocs.org/user-guide/configuration/#live-reloading), huge convenience when seeing docs locally. Thoughts?

It should be turned on at least for the main contents; I think because of how docstrings are generated, this might not be working properly. But I'm happy accepting PRs fixing that (It's not counted as part of unitary hack tho given it's not been listed)

2024-06-03 21:33 UTC, merged