Improve Docstrings task/quera.py #957
QuEraComputing/bloqade-python pull request #971
Opened 2024-05-31 04:32 UTC by shubhusion

Fixes #957 
Improve Docstrings, Remove Markdown Errors

2024-05-31 06:00 UTC, shubhusion commented
@Roger-luo please review this

2024-06-03 16:08 UTC, weinbe58 requested changes
Overall looks good, just need to address the comments.

2024-06-03 16:08 UTC, weinbe58 commented on src/bloqade/task/quera.py
> +        Forcefully pulls the task results from the backend.
```suggestion
        Blocks execution until task is in a stopped state, e.g. Completed, Cancelled, Failed, etc.
```

Wrong behavior, this function is used to Poll the remote API until the task is completed.

2024-06-03 16:08 UTC, weinbe58 commented on src/bloqade/task/quera.py
> +    """
you don't need to document these private functions.

2024-06-03 16:08 UTC, weinbe58 commented on src/bloqade/task/quera.py
> +    """
same here.

2024-06-03 17:36 UTC, shubhusion commented
@weinbe58 I have addressed the changes as requested by you

2024-06-03 19:31 UTC, Roger-luo requested changes
I think like the other PR, we should have some examples demonstrating how to use these APIs instead of just plain explanations.

2024-06-03 19:32 UTC, Roger-luo commented
I'm going to comment on your other PRs with the same comment as following to avoid duplicated review comments for other reviewers:

I think you should work on #975 first instead of asking people to review other PRs, so we don't resolve duplicated issues in multiple PRs.

2024-06-03 19:50 UTC, shubhusion commented
> I'm going to comment on your other PRs with the same comment as following to avoid duplicated review comments for other reviewers:
> 
> I think you should work on #975 first instead of asking people to review other PRs, so we don't resolve duplicated issues in multiple PRs.

@Roger-luo I just addressed all the requirements @weinbe58 mentioned. I am working on other PRs where you have mentioned changes related to examples.

2024-08-02 13:23 UTC, closed without merging