Improve docstrings for "task/bloqade"
QuEraComputing/bloqade-python pull request #973
Opened 2024-05-31 06:47 UTC by shubhusion

Fixes #957 

Improves Docstrings and Remove Markdown errors.

2024-05-31 15:51 UTC, Roger-luo commented on src/bloqade/task/bloqade.py
> +    """
I think these private methods are self-explainable, we don't have to add docstrings to them.

2024-05-31 15:54 UTC, Roger-luo requested changes
I'd recommend to finish one of the PRs first instead of submitting a bunch of them to review, so you don't waste any effort and we don't need to review similar issues multiple times. The docstrings in tasks are harder to write as they are deeper in the codebase. I'd recommend you to go through some basic tutorial before going ahead so we make docstring friendly to new comers other than just plain explanation of what the code does.

2024-05-31 16:02 UTC, shubhusion commented
> I'd recommend to finish one of the PRs first instead of submitting a bunch of them to review, so you don't waste any effort and we don't need to review similar issues multiple times. The docstrings in tasks are harder to write as they are deeper in the codebase. I'd recommend you to go through some basic tutorial before going ahead so we make docstring friendly to new comers other than just plain explanation of what the code does.

@Roger-luo can you provide a link to tutorials which i can refer to ?

2024-05-31 16:28 UTC, Roger-luo commented
https://queracomputing.github.io/bloqade-python-examples/latest/ you can also check the quick start guide in the documentation homepage to understand better what this package does.

2024-06-03 19:09 UTC, shubhusion commented
@Roger-luo I have made changes in this PR as requested by you.

2024-06-03 19:35 UTC, Roger-luo requested changes
Please try to finish one PR before requesting reviews on multiple ones, otherwise this will result in duplicated review comments that are hard to manage.

2024-06-03 19:35 UTC, Roger-luo commented on src/bloqade/task/bloqade.py
> +        """
this is a private function

2024-06-03 19:35 UTC, Roger-luo commented on src/bloqade/task/bloqade.py
> +        """
please also add one example to demonstrate how this function can be used. This is a user API.

2024-08-02 13:23 UTC, closed without merging